### PR TITLE
New CUDA CI+development Docker container

### PR DESCRIPTION
**Pull request by BenWibking**
## PR Summary

Updates the CUDA CI image to CUDA 12.8, Ubuntu 24.04, and Clang 20, and adds a GitHub action to build and push the image.

Adds a ` .devcontainer/devcontainer.json` file to support [GitHub Codespaces](https://docs.github.com/en/codespaces) and VSCode [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) out of the box.

This container can be built as a multi-arch image for both x86_64 and ARM support, e.g.:
```
docker build --file Dockerfile.nvcc --tag parthenon-hpc-lab/cuda12.8-mpi-hdf5-ascent --platform linux/amd64,linux/arm64 .
```

The updated containers also contain ADIOS2 and OpenPMD.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by BenWibking** [comment]
Without `--platform linux/amd64`, it fails on my Mac laptop with:
```
 => ERROR [11/14] RUN mkdir /tmp/build-adios2 && cd /tmp/build-adios2 &&     git clone https://github.com/ornladios/ADIOS2.git ADIOS2  3.3s
------
 > [11/14] RUN mkdir /tmp/build-adios2 && cd /tmp/build-adios2 &&     git clone https://github.com/ornladios/ADIOS2.git ADIOS2 &&     mkdir adios2-build && cd adios2-build &&     cmake ../ADIOS2 -DADIOS2_USE_Blosc2=ON -DADIOS2_USE_Fortran=OFF &&     make -j8 && make install &&     cd / &&     rm -rf /tmp/build-adios2:
0.101 Cloning into 'ADIOS2'...
3.223 rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
3.223  Trace/breakpoint trap
------
Dockerfile.nvcc:47
--------------------
```
so I'm not sure how to do an aarch64 build of this.

**Comment by BenWibking** [comment]
openPMD build currently fails with an internal compiler error:
```
239.7       [100%] Linking CXX shared module /tmp/pip-install-4ic7_hio/openpmd-api_babdc26b91414db2ab4c842215a7206e/build/lib.linux-x86_64-cpython-312/openpmd_api/openpmd_api_cxx.cpython-312-x86_64-linux-gnu.so
239.7       lto1: internal compiler error: in return_token, at opts-common.cc:2135
239.7       0x19bb73a internal_error(char const*, ...)
239.7           ???:0
239.7       0x683a32 fancy_abort(char const*, int, char const*)
239.7           ???:0
239.7       0x6ba314 lto_main()
239.7           ???:0
239.7       Please submit a full bug report, with preprocessed source (by using -freport-bug).
239.7       Please include the complete backtrace with any bug report.
239.7       See <file:///usr/share/doc/gcc-13/README.Bugs> for instructions.
239.7       lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
239.7       compilation terminated.
239.7       /usr/bin/ld: error: lto-wrapper failed
239.7       collect2: error: ld returned 1 exit status
239.7       gmake[2]: *** [CMakeFiles/openPMD.py.dir/build.make:453: /tmp/pip-install-4ic7_hio/openpmd-api_babdc26b91414db2ab4c842215a7206e/build/lib.linux-x86_64-cpython-312/openpmd_api/openpmd_api_cxx.cpython-312-x86_64-linux-gnu.so] Error 1
239.7       gmake[1]: *** [CMakeFiles/Makefile2:920: CMakeFiles/openPMD.py.dir/all] Error 2
239.7       gmake: *** [Makefile:146: all] Error 2
```

**Comment by BenWibking** [comment]
Ascent cannot be compiled with CUDA 12.4+, because VTK-m does not support it (https://gitlab.kitware.com/vtk/vtk-m/-/issues/790).

vtk-m also fails to build with gcc 12+:
```
56.81 [  8%] Building CXX object vtkm/cont/CMakeFiles/vtkm_cont.dir/DataSetBuilderUniform.cxx.o
56.81 cd /usr/local/build/vtk-m-v2.1.0/vtkm/cont && /usr/bin/g++ -DVTKMDIY_MPI_AS_LIB -DVTKMDIY_NO_THREADS -Dvtkm_cont_EXPORTS -I/usr/local/source/vtk-m-v2.1.0/vtkm/thirdparty/optionparser -I/usr/local/source/vtk-m-v2.1.0/vtkm/thirdparty/diy -I/usr/local/source/vtk-m-v2.1.0/vtkm/thirdparty/lcl/vtkmlcl -I/usr/local/source/vtk-m-v2.1.0/vtkm/thirdparty/loguru -I/usr/local/source/vtk-m-v2.1.0 -I/usr/local/build/vtk-m-v2.1.0/include -isystem /usr/local/source/vtk-m-v2.1.0/vtkm/thirdparty/diy/vtkmdiy/include -isystem /usr/local/build/vtk-m-v2.1.0/vtkm/thirdparty/diy/vtkmdiy/include/vtkmdiy/mpi -O3 -DNDEBUG -std=c++14 -fPIC -fvisibility=hidden -Wall -Wcast-align -Wextra -Wpointer-arith -Wformat -Wformat-security -Wshadow -Wunused -fno-common -Wno-unused-function -Wchar-subscripts -Wfloat-conversion -Wodr -ffunction-sections -MD -MT vtkm/cont/CMakeFiles/vtkm_cont.dir/DataSetBuilderUniform.cxx.o -MF CMakeFiles/vtkm_cont.dir/DataSetBuilderUniform.cxx.o.d -o CMakeFiles/vtkm_cont.dir/DataSetBuilderUniform.cxx.o -c /usr/local/source/vtk-m-v2.1.0/vtkm/cont/DataSetBuilderUniform.cxx
56.84 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/ThrustPatches.h(213): error: this declaration has no storage class or type specifier
56.84     __thrust_exec_check_disable__
56.84     ^
56.84
56.84 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/ThrustPatches.h(214): warning #1835-D: attribute "__host__" does not apply here
56.84       __attribute__((host)) __attribute__((device))
56.84                      ^
56.84
56.84 Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"
56.84
56.84 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/ThrustPatches.h(214): warning #1835-D: attribute "__device__" does not apply here
56.84       __attribute__((host)) __attribute__((device))
56.84                                            ^
56.84
56.84 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/ThrustPatches.h(215): error: expected a ";"
56.84       stateless_resource_allocator()
56.84       ^
56.84
56.84 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/ThrustPatches.h(236): warning #12-D: parsing restarts here after previous syntax error
56.84   };
56.84   ^
56.84
56.97 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/WrappedOperators.h(198): error: namespace "thrust::THRUST_200500_800_NS::detail" has no member class "is_arithmetic"
56.97     : public thrust::detail::is_arithmetic<T>
56.97                              ^
56.97
56.97 /usr/local/source/vtk-m-v2.1.0/vtkm/exec/cuda/internal/WrappedOperators.h(198): error: class or struct definition is missing
56.97     : public thrust::detail::is_arithmetic<T>
56.97                                           ^
```

**Comment by BenWibking** [comment]
@pgrete do we need Ascent in the CI container anymore? it doesn't appear to work with either CUDA 12.6 or gcc 12+.

**Comment by BenWibking** [comment]
Downgrading to gcc-11 works around the OpenPMD internal compiler error issue, but I now get a strange "bad file descriptor" issue:
```
219.8       [100%] Linking CXX shared module /tmp/pip-install-83a2m_zw/openpmd-api_787390c9923e43d99acad670315692e7/build/lib.linux-x86_64-cpython-312/openpmd_api/openpmd_api_cxx.cpython-312-x86_64-linux-gnu.so
219.8       make[3]: *** write jobserver: Bad file descriptor.  Stop.
219.8       make[3]: *** Waiting for unfinished jobs....
219.8       make[3]: *** write jobserver: Bad file descriptor.  Stop.
219.8       lto-wrapper: fatal error: make returned 2 exit status
219.8       compilation terminated.
219.8       /usr/bin/ld: error: lto-wrapper failed
219.8       collect2: error: ld returned 1 exit status
```

**Comment by pgrete** [comment]
Given that we still support Ascent (and still in principle interested in using it), it'd be great if we could keep it.
Also based on the spack recipe and and some issue on Github I'm under the impression that it should work with Cuda 12.
I'm wondering if it's possible to get the entire software stack build with spack in a single line (and then just keep the libs/binaries in the container).

**Comment by BenWibking** [comment]
> Given that we still support Ascent (and still in principle interested in using it), it'd be great if we could keep it. Also based on the spack recipe and and some issue on Github I'm under the impression that it should work with Cuda 12. I'm wondering if it's possible to get the entire software stack build with spack in a single line (and then just keep the libs/binaries in the container).

The Gitlab VTK-m issues suggest it doesn't work with CUDA 12.4 or 12.5, and it failed for me with 12.6. Maybe it works with earlier minor versions. However, 12.6 is the only version that has an Ubuntu 24.04 container.

Feel free to push changes to this branch -- I can't work on this more at the moment.

**Comment by BenWibking** [comment]
@pgrete However, everything except Ascent works now, both on x86-64 and arm64.

**Comment by BenWibking** [comment]
I've checked that Ascent builds with CUDA 12.0. So it stops working somewhere between CUDA 12.1-12.4.

**Comment by pgrete** [comment]
Thanks for tackling the version inconsistencies.
With regard to the content of the PR itself, I suggest to fix the versions (e.g. of adios2 and openpmd) so that the script also works when executed in the future.
Also, I looked at the diff between the `build_ascent.sh` in the PR and the one in the Ascent repo.
How about fixing the version of Ascent, the get a copy of that version, apply a few line patch and compile from there?
I'm happy you make those changes if you agree (you already did the heavily lifting in figuring out what's compatible).

**Comment by BenWibking** [comment]
> Thanks for tackling the version inconsistencies. With regard to the content of the PR itself, I suggest to fix the versions (e.g. of adios2 and openpmd) so that the script also works when executed in the future.

adios2 and openpmd build now with the version in this PR.

>Also, I looked at the diff between the `build_ascent.sh` in the PR and the one in the Ascent repo. How about fixing the version of Ascent, the get a copy of that version, apply a few line patch and compile from there?

I don't follow your suggestion. Can you explain what you mean by this?  Do you want us to download the build_ascent.sh script from the Ascent repo and then apply a patch to it?

**Comment by BenWibking** [comment]
@pgrete Everything builds now if I set `enable_cuda=OFF` in the Ascent build. It fails when `enable_cuda=ON` for both ARM and x86-64 Docker image builds.

~~I can't easily test x86_64 Docker builds with Ascent CUDA support, since those build *extremely* slowly on my (M1) Mac laptop. Can you try an x86_64 Docker image build?~~

*Update*: The issue is that when CUDA support for Ascent is enabled, the compiler is OOM killed. I am running Docker with resource settings set to 12 GB RAM and 1 GB swap. This is apparently not enough. The actual error message is:
```
Killed
	gmake[2]: *** [vtkm/filter/flow/CMakeFiles/vtkm_filter_flow.dir/build.make:163: vtkm/filter/flow/CMakeFiles/vtkm_filter_flow.dir/FilterParticleAdvectionUnsteadyState.cxx.o] Error 137
```

File: scripts/docker/Dockerfile.nvcc [hunk 1]
```diff
@@ -36,19 +41,28 @@ RUN cd /tmp && \
...
-ENV PATH=/opt/cmake-3.23.2-linux-x86_64/bin:$PATH
+COPY ascent_build /tmp/ascent_build
 
-COPY build_ascent_cuda.sh /tmp/build-ascent/build_ascent_cuda.sh
+## NOTE: with enable_cuda=ON, arm64 Dockerfile builds fail for some reason
 
-RUN cd /tmp/build-ascent && \
-    bash build_ascent_cuda.sh && \
+RUN cd /tmp/ascent_build && \
+    env enable_cuda=ON bash build_ascent.sh && \
```
Comment (BenWibking) [inline scripts/docker/Dockerfile.nvcc]: This works for me when `enable_cuda=OFF`, but currently fails with an OOM kill when it is `ON`.

**Comment by BenWibking** [comment]
@pgrete I finally got it to build with 15 GB of RAM and 4 GB of swap (for the Docker VM). Can you build it and verify that it works, and if so, upload it to DockerHub?

**Comment by pgrete** [comment]
I just pushed the changes I had in mind (using the build script from the Ascent src with a small patch) and using fixed version for ADIOS2 and OpenPMD.
Everything (the docker) builds BUT it doesn't work with Parthenon...
```bash
$ cmake -B build-ascent -DCMAKE_BUILD_TYPE=Release -DMACHINE_VARIANT=cuda-mpi -DMACHINE_CFG=$(pwd)/cmake/machinecfg/CI.cmake -DPARTHENON_ENABLE_ASCENT=ON -DAscent_DIR=/usr/local/ascent-checkout/lib/cmake/ascent

...

-- Building performance tests.
-- Building regression tests.
-- Creating BLT MPI targets...
-- FindMPI Enabled  (ENABLE_FIND_MPI == ON)
-- Found MPI_C: /opt/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- BLT MPI Compile Flags:  
-- BLT MPI Include Paths:  /opt/openmpi/include
-- BLT MPI Libraries:      /opt/openmpi/lib/libmpi.so
-- BLT MPI Link Flags:     SHELL:-Wl,-rpath -Wl,/opt/openmpi/lib -Wl,--enable-new-dtags
-- MPI Executable:       /opt/openmpi/bin/mpiexec
-- MPI Num Proc Flag:    -n
-- MPI Command Append:   
-- Creating BLT CUDA targets...
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:726 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda/bin/nvcc

  Build flags:

  Id flags:
  --keep;--keep-dir;tmp;-ccbin=/parthenon/external/Kokkos/bin/nvcc_wrapper -v

  

  The output was:

  2

  #$ _NVVM_BRANCH_=nvvm

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/local/cuda/bin

  #$ _THERE_=/usr/local/cuda/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_DIR_=targets/x86_64-linux

  #$ TOP=/usr/local/cuda/bin/..

  #$ NVVMIR_LIBRARY_DIR=/usr/local/cuda/bin/../nvvm/libdevice

  #$
  LD_LIBRARY_PATH=/usr/local/cuda/bin/../lib:/opt/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64


  #$
  PATH=/usr/local/cuda/bin/../nvvm/bin:/usr/local/cuda/bin:/opt/openmpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


  #$ INCLUDES="-I/usr/local/cuda/bin/../targets/x86_64-linux/include"

  #$ LIBRARIES= "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib/stubs"
  "-L/usr/local/cuda/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$ "/parthenon/external/Kokkos/bin"/nvcc_wrapper -D__CUDA_ARCH_LIST__=520
  -E -x c++ -D__CUDACC__ -D__NVCC__
  "-I/usr/local/cuda/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=0
  -D__CUDACC_VER_BUILD__=140 -D__CUDA_API_VER_MAJOR__=12
  -D__CUDA_API_VER_MINOR__=0 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include
  "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" -o
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  <command-line>: warning: "__CUDA_ARCH_LIST__" redefined

  <command-line>: note: this is the location of the previous definition

  #$ cudafe++ --c++17 --gnu_version=110400 --display_error_number
  --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/parthenon/build-ascent/CMakeFiles/3.22.1/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed --m64 --parse_templates --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name
  "CMakeCUDACompilerId.cudafe1.stub.c" --gen_module_id_file
  --module_id_file_name "tmp/CMakeCUDACompilerId.module_id"
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(94):
  error: identifier "__match32_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(98):
  error: identifier "__match32_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(103):
  error: identifier "__match64_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(104):
  error: identifier "__match32_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(109):
  error: identifier "__match64_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(110):
  error: identifier "__match32_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(114):
  error: identifier "__match64_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(118):
  error: identifier "__match64_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(122):
  error: identifier "__match32_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(126):
  error: identifier "__match64_any_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(133):
  error: identifier "__match32_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(137):
  error: identifier "__match32_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(142):
  error: identifier "__match64_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(143):
  error: identifier "__match32_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(148):
  error: identifier "__match64_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(149):
  error: identifier "__match32_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(153):
  error: identifier "__match64_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(157):
  error: identifier "__match64_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(161):
  error: identifier "__match32_all_sync" is undefined

  

  /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(165):
  error: identifier "__match64_all_sync" is undefined

  

  20 errors detected in the compilation of "CMakeCUDACompilerId.cu".

  # --error 0x2 --

  

  

Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID)
  /usr/local/ascent-checkout/lib/cmake/ascent/thirdparty/BLTSetupCUDA.cmake:67 (enable_language)
  /usr/local/ascent-checkout/lib/cmake/ascent/BLTSetupTargets.cmake:97 (include)
  /usr/local/ascent-checkout/lib/cmake/ascent/AscentConfig.cmake:156 (include)
  CMakeLists.txt:370 (find_package)


-- Configuring incomplete, errors occurred!
See also "/parthenon/build-ascent/CMakeFiles/CMakeOutput.log".
See also "/parthenon/build-ascent/CMakeFiles/CMakeError.log".

```

I don't get it...

```bash
$ cat/parthenon/build-ascent/CMakeFiles/CMakeError.log

#$ "/parthenon/external/Kokkos/bin"/nvcc_wrapper -D__CUDA_ARCH_LIST__=520 -E -x c++ -D__CUDACC__ -D__NVCC__  "-I/usr/local/cuda/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=0 -D__CUDACC_VER_BUILD__=140 -D__CUDA_API_VER_MAJOR__=12 -D__CUDA_API_VER_MINOR__=0 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp4.ii" 
<command-line>: warning: "__CUDA_ARCH_LIST__" redefined
<command-line>: note: this is the location of the previous definition
#$ cudafe++ --c++17 --gnu_version=110400 --display_error_number --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name "/parthenon/build-ascent/CMakeFiles/3.22.1/CompilerIdCUDA/CMakeCUDACompilerId.cu" --allow_managed  --m64 --parse_templates --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name "CMakeCUDACompilerId.cudafe1.stub.c" --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" "tmp/CMakeCUDACompilerId.cpp4.ii" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(94): error: identifier "__match32_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(98): error: identifier "__match32_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(103): error: identifier "__match64_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(104): error: identifier "__match32_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(109): error: identifier "__match64_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(110): error: identifier "__match32_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(114): error: identifier "__match64_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(118): error: identifier "__match64_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(122): error: identifier "__match32_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(126): error: identifier "__match64_any_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(133): error: identifier "__match32_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(137): error: identifier "__match32_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(142): error: identifier "__match64_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(143): error: identifier "__match32_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(148): error: identifier "__match64_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(149): error: identifier "__match32_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(153): error: identifier "__match64_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(157): error: identifier "__match64_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(161): error: identifier "__match32_all_sync" is undefined

/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/sm_70_rt.hpp(165): error: identifier "__match64_all_sync" is undefined

20 errors detected in the compilation of "CMakeCUDACompilerId.cu".
# --error 0x2 --
```

**Comment by BenWibking** [comment]
Just wondering, why is the CUDA_ARCH set to `520`: `-D__CUDA_ARCH_LIST__=520`?

Maybe a CUDA 12.0 bug?

**Comment by BenWibking** [comment]
One change I wanted to make was to have it run insider the container by default as a non-root user. This avoids the OpenMPI warnings about running as root user, and also prevents container users from accidentally destroying system packages, or the pre-installed dependencies.

**Comment by BenWibking** [comment]
Since Parthenon builds without Ascent support enabled in the container, I think this is an Ascent (or maybe BLT) bug.

I have no interest in Ascent support, so I can't debug this any further.

**Comment by BenWibking** [comment]
I wonder if it is possible to reproduce this with the BLT CalcPi tutorial: https://github.com/LLNL/blt/tree/develop/docs/tutorial/calc_pi

**Comment by BenWibking** [comment]
I can't reproduce with BLT alone. It also doesn't work on CUDA 12.1 for me.

My guess is that this is an Ascent bug introduced in the past few months that only manifests for Kokkos apps.

**Comment by acreyes** [comment]
> Just wondering, why is the CUDA_ARCH set to `520`: `-D__CUDA_ARCH_LIST__=520`?
> 
> Maybe a CUDA 12.0 bug?

I think this is just what cmake uses to check the cuda compiler because it is the default in `nvcc`. The error looks like its trying to use headers for `sm_70` architecture. I think this is the default for kokkos' `nvcc_wrapper` and maybe this is why the problem is only when building parthenon (with `CMAKE_CXX_COMPILER=nvcc_wrapper`)?

**Comment by pgrete** [comment]
I'm going to ask the Ascent devs.

**Comment by BenWibking** [comment]
VTK-m is supposed to work with CUDA 12 now: https://gitlab.kitware.com/vtk/vtk-m/-/issues/790

**Comment by BenWibking** [comment]
FYI- I just built the latest development Ascent + VTK-m with CUDA 12.8 and GCC 12.3 for Hopper. It seems to work now.

**Comment by BenWibking** [comment]
@pgrete I think this works now. If you get a chance, can you test this on the CI machine?

**Comment by BenWibking** [comment]
Ok, it fails at the very end:
```
 => ERROR [18/19] RUN useradd --create-home --shell /bin/bash -u 1000 -G render,sudo ci                                                                         0.1s
------
 > [18/19] RUN useradd --create-home --shell /bin/bash -u 1000 -G render,sudo ci:
0.120 useradd: UID 1000 is not unique
------
Dockerfile.nvcc:92
--------------------
  90 |     # uid 1000 maps to the one running the container on the CI host
  91 |     RUN groupadd -g 109 render
  92 | >>> RUN useradd --create-home --shell /bin/bash -u 1000 -G render,sudo ci
  93 |
  94 |     USER ci
--------------------
ERROR: failed to solve: process "/bin/sh -c useradd --create-home --shell /bin/bash -u 1000 -G render,sudo ci" did not complete successfully: exit code: 4
```

I worked around this by removing `-u 1000`. So now we still have user `ci`, but it has a different uid. I'm not sure whether this is important when running in Docker.

**Comment by pgrete** [comment]
@BenWibking do you think the publish will work (given the mem requirements)? Is there a way to test this before it's part of `develop`?

**Comment by BenWibking** [comment]
> @BenWibking do you think the publish will work (given the mem requirements)? Is there a way to test this before it's part of `develop`?

Probably not. I just decided to delete it.

**Comment by pgrete** [comment]
This feels like going in circles (again)...

Any clue what's going on here? https://github.com/parthenon-hpc-lab/parthenon/actions/runs/14491789751/job/40649691365

Do you have an Ascent runner for Quokka?

**Comment by BenWibking** [comment]
> This feels like going in circles (again)...
> 
> Any clue what's going on here? https://github.com/parthenon-hpc-lab/parthenon/actions/runs/14491789751/job/40649691365
> 
> Do you have an Ascent runner for Quokka?

Ah, this again...

For Quokka, I haven't set up a CI runner that includes Ascent.

**Comment by BenWibking** [comment]
> This feels like going in circles (again)...
> 
> Any clue what's going on here? https://github.com/parthenon-hpc-lab/parthenon/actions/runs/14491789751/job/40649691365
> 
> Do you have an Ascent runner for Quokka?

@pgrete I tried setting up an Ascent runner for Quokka here, but encountered similarly strange build issues: https://github.com/quokka-astro/quokka/pull/1018

**Comment by BenWibking** [comment]
Our build issues were fixed by setting `-DCMAKE_CUDA_HOST_COMPILER=g++` explicitly.

I'm guessing the Kokkos `nvcc_wrapper` is interfering with BLT's mechanisms for detecting the CUDA device compiler...

**Comment by pgrete** [comment]
This stack is a mess...

The BLT fix worked, but now it fails with
```
 ../../build-ascent/example/advection/advection-example: symbol lookup error: ../../build-ascent/example/advection/advection-example: undefined symbol: H5Pset_dxpl_mpio
```

Seems like all kind of HDF5 libs are being picked up... buy one get one free...

```
 -- Found HDF5: /usr/local/hdf5/parallel/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.12.2")  
-- HDF5_DIR_REAL=/usr/local/hdf5/serial
-- Checking that found HDF5_INCLUDE_DIRS are in HDF5_DIR
-- HDF5_INCLUDE_DIRS=/usr/local/hdf5/parallel/include
--  /usr/local/hdf5/parallel/include includes HDF5_REAL_DIR ()
-- HDF5 is parallel:  TRUE
-- Found Conduit: /usr/local/conduit-v0.9.3 (found version 0.9.3)
-- CONDUIT_VERSION             = 0.9.3
-- CONDUIT_INSTALL_PREFIX      = /usr/local/conduit-v0.9.3
-- CONDUIT_IMPORT_ROOT         = /usr/local/conduit-v0.9.3
-- CONDUIT_USE_CXX14           = TRUE
-- CONDUIT_USE_FMT             = TRUE
-- CONDUIT_INCLUDE_DIRS        = /usr/local/conduit-v0.9.3/include/conduit
-- CONDUIT_FORTRAN_ENABLED     = FALSE
-- CONDUIT_PYTHON_ENABLED      = 
-- CONDUIT_PYTHON_EXECUTABLE   = 
-- CONDUIT_PYTHON_MODULE_DIR   = /usr/local/conduit-v0.9.3/python-modules/
-- Conduit Relay features:
--  CONDUIT_RELAY_WEBSERVER_ENABLED = TRUE
--  CONDUIT_RELAY_HDF5_ENABLED      = TRUE
--  CONDUIT_HDF5_DIR                = /usr/local/hdf5/serial
```

I wonder if it's easier to use some ascent container as baseline (just for the ascent test).

**Comment by BenWibking** [comment]
We are planning to migrate to using Viskores directly for volume rendering, in order to avoid this. The downside is you do have to render each MeshBlock separately with Viskores, then composite the final image in parallel, either yourself, or using a separate library like [IceT](https://gitlab.kitware.com/icet/icet). But that's 2 extra dependencies, rather than 10-20.

**Comment by pgrete** [comment]
Houston, we have a build!
(the serial version of hd5 was passed manually, which caused the latest issue).

I now also added openpmd (and adios2) to all containers in anticipation of #1050 

I think this is ready for review now.

**Review by Yurlungur — APPROVED** [review]
LGTM

**Comment by pgrete** [comment]
@BenWibking could you please do a quick "review" of the final changes (i.e., make a comment here as you cannot technially review as the author of the PR)?
I'll then approve and merge.

**Comment by BenWibking** [comment]
Looks good to me.

**Comment by pgrete** [comment]
Great, thanks!

**Review by pgrete — APPROVED** [review]
