### PR TITLE
Allow for `ParArrayGeneric::operator(...)` and `ParArrayGeneric::Get(...)` to accept `enum`s 

### LINKED ISSUE #701: `ParArrayGeneric` parenthesis operator broken for enum type indices?
While reviewing the sparse comm PR I noticed that AthenaPK does not build anymore.
It looks like there's a connection to the default constructors introduced in #681
One of the error messages is:
```
FAILED: src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o 
/usr/bin/clang++ -DKOKKOS_DEPENDENCE -I/home/pgrete/src/athenapk/external/parthenon/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/src/generated -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src/../../tpls/desul/include -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/containers/src -I/home/pgrete/src/athenapk/external/Kokkos/containers/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/algorithms/src -I/home/pgrete/src/athenapk/external/Kokkos/algorithms/src -fopenmp-simd -O3 -DNDEBUG -march=skylake-avx512 -mtune=skylake-avx512 -std=c++17 -MD -MT src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o -MF src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o.d -o src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o -c /home/pgrete/src/athenapk/src/hydro/srcterms/tabular_cooling.cpp
/home/pgrete/src/athenapk/src/hydro/srcterms/tabular_cooling.cpp:608:20: error: no matching constructor for initialization of 'ParArray2D<parthenon::Real>' (aka 'ParArrayGeneric<View<double **, Kokkos::LayoutRight, Kokkos::HostSpace>, parthenon::empty_state_t>')
  ParArray2D<Real> d_rho("d_rho", n_rho, n_pres);
                   ^     ~~~~~~~~~~~~~~~~~~~~~~
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:140:3: note: candidate template ignored: requirement 'all_implement<integral (double), void>::value' was not satisfied [with Args = <double>, $1 = 0, $2 = 0]
  ParArrayGeneric(const std::string &label, const State &state, Args... args)
  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:277:3: note: candidate template ignored: could not match 'std::index_sequence<I...>' (aka 'integer_sequence<unsigned long, I...>') against 'parthenon::Real' (aka 'double')
  ParArrayGeneric(const std::string &label, const State &state, std::index_sequence<I...>,
  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:72:12: note: candidate constructor not viable: requires at most 2 arguments, but 3 were provided
  explicit ParArrayGeneric(const Data &v, const State &state = State())
           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:119:12: note: candidate constructor template not viable: requires at most 2 arguments, but 3 were provided
  explicit ParArrayGeneric(const std::string & /*label*/, const State &state = State())
           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:130:3: note: candidate template ignored: requirement 'all_implement<integral (double, double), void>::value' was not satisfied [with Args = <double, double>, $1 = 0, $2 = 0]
  ParArrayGeneric(const std::string &label, Args... args)
  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:66:28: note: candidate constructor not viable: requires single argument 't', but 3 arguments were provided
  __attribute__((nothrow)) ParArrayGeneric(const ParArrayGeneric &t) = default;
                           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:68:28: note: candidate constructor not viable: requires single argument 't', but 3 arguments were provided
  __attribute__((nothrow)) ParArrayGeneric(ParArrayGeneric &&t) = default;
                           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:76:35: note: candidate constructor template not viable: requires single argument 'arr_in', but 3 arguments were provided
  KOKKOS_INLINE_FUNCTION explicit ParArrayGeneric(
                                  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:123:35: note: candidate constructor template not viable: requires single argument 'state', but 3 arguments were provided
  KOKKOS_INLINE_FUNCTION explicit ParArrayGeneric(const State &state)
                                  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:64:3: note: candidate constructor not viable: requires 0 arguments, but 3 were provided
  ParArrayGeneric() = default;
```

I'm not sure where this error comes from nor why we didn't catch this in the existing tests. Using a `ParArary#D` seems like a usecase we should provide.

Any thoughts @lroberts36 

(Probably independently but related) our default access pattern to variables like
```
w(IPR, k, j, i + 1) ;
// with
// enum { IV1 = 1, IV2 = 2, IV3 = 3, IPR = 4 };
```
does not work any more resuling in the following error
```
FAILED: src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o 
/usr/bin/clang++ -DKOKKOS_DEPENDENCE -I/home/pgrete/src/athenapk/external/parthenon/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/src/generated -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src/../../tpls/desul/include -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/containers/src -I/home/pgrete/src/athenapk/external/Kokkos/containers/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/algorithms/src -I/home/pgrete/src/athenapk/external/Kokkos/algorithms/src -fopenmp-simd -O3 -DNDEBUG -march=skylake-avx512 -mtune=skylake-avx512 -std=c++17 -MD -MT src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o -MF src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o.d -o src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o -c /home/pgrete/src/athenapk/src/refinement/gradient.cpp
/home/pgrete/src/athenapk/src/refinement/gradient.cpp:36:43: error: no matching function for call to object of type 'const ParArrayND<double>' (aka 'const ParArrayGeneric<View<double ******, Kokkos::LayoutRight, Kokkos::HostSpace>, parthenon::empty_state_t>')
          Real eps = std::sqrt(SQR(0.5 * (w(IPR, k, j, i + 1) - w(IPR, k, j, i - 1))) +
                                          ^
/home/pgrete/src/athenapk/build-vscode/parthenon/src/generated/config.hpp:82:19: note: expanded from macro 'SQR'
#define SQR(x) ( (x) * (x) )
                  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:175:37: note: candidate template ignored: requirement 'all_implement<integral ((unnamed enum at /home/pgrete/src/athenapk/src/refinement/../main.hpp:31:1), int, int, int), void>::value' was not satisfied [with Args = <(unnamed enum at /home/pgrete/src/athenapk/src/refinement/../main.hpp:31:1), int, int, int>]
  KOKKOS_FORCEINLINE_FUNCTION auto &operator()(Args... args) const {
```

I'm currently wondering if we should update AthenaPK or update Parthenon (whereas the latter would imply a certain style in downstream codes). Any thoughts anyone?

Ping @jdolence @lroberts36 @Yurlungur @forrestglines

### PR DESCRIPTION
**Pull request by lroberts36**
## PR Summary
This PR fixes issue #701. It adds support for indexing into `ParArrayGeneric` using both c-style `enum`s and `enum class`s that have an underlying type that is integral (I think the latter may not have been possible even before #681). 

@pgrete: Please check this with `AthenaPK` and see if it fixes the issue you were seeing.     

## PR Checklist

- [x] Code passes cpplint
- [x] Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by pgrete — APPROVED** [review]
Thanks for the quick fix!
I can confirm that this make AthenaPK happy.

**Review by Yurlungur — APPROVED** [review]
