### ISSUE TITLE
`ParArrayGeneric` parenthesis operator broken for enum type indices?

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#701]
While reviewing the sparse comm PR I noticed that AthenaPK does not build anymore.
It looks like there's a connection to the default constructors introduced in #681
One of the error messages is:
```
FAILED: src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o 
/usr/bin/clang++ -DKOKKOS_DEPENDENCE -I/home/pgrete/src/athenapk/external/parthenon/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/src/generated -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src/../../tpls/desul/include -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/containers/src -I/home/pgrete/src/athenapk/external/Kokkos/containers/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/algorithms/src -I/home/pgrete/src/athenapk/external/Kokkos/algorithms/src -fopenmp-simd -O3 -DNDEBUG -march=skylake-avx512 -mtune=skylake-avx512 -std=c++17 -MD -MT src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o -MF src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o.d -o src/CMakeFiles/athenaPK.dir/hydro/srcterms/tabular_cooling.cpp.o -c /home/pgrete/src/athenapk/src/hydro/srcterms/tabular_cooling.cpp
/home/pgrete/src/athenapk/src/hydro/srcterms/tabular_cooling.cpp:608:20: error: no matching constructor for initialization of 'ParArray2D<parthenon::Real>' (aka 'ParArrayGeneric<View<double **, Kokkos::LayoutRight, Kokkos::HostSpace>, parthenon::empty_state_t>')
  ParArray2D<Real> d_rho("d_rho", n_rho, n_pres);
                   ^     ~~~~~~~~~~~~~~~~~~~~~~
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:140:3: note: candidate template ignored: requirement 'all_implement<integral (double), void>::value' was not satisfied [with Args = <double>, $1 = 0, $2 = 0]
  ParArrayGeneric(const std::string &label, const State &state, Args... args)
  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:277:3: note: candidate template ignored: could not match 'std::index_sequence<I...>' (aka 'integer_sequence<unsigned long, I...>') against 'parthenon::Real' (aka 'double')
  ParArrayGeneric(const std::string &label, const State &state, std::index_sequence<I...>,
  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:72:12: note: candidate constructor not viable: requires at most 2 arguments, but 3 were provided
  explicit ParArrayGeneric(const Data &v, const State &state = State())
           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:119:12: note: candidate constructor template not viable: requires at most 2 arguments, but 3 were provided
  explicit ParArrayGeneric(const std::string & /*label*/, const State &state = State())
           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:130:3: note: candidate template ignored: requirement 'all_implement<integral (double, double), void>::value' was not satisfied [with Args = <double, double>, $1 = 0, $2 = 0]
  ParArrayGeneric(const std::string &label, Args... args)
  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:66:28: note: candidate constructor not viable: requires single argument 't', but 3 arguments were provided
  __attribute__((nothrow)) ParArrayGeneric(const ParArrayGeneric &t) = default;
                           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:68:28: note: candidate constructor not viable: requires single argument 't', but 3 arguments were provided
  __attribute__((nothrow)) ParArrayGeneric(ParArrayGeneric &&t) = default;
                           ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:76:35: note: candidate constructor template not viable: requires single argument 'arr_in', but 3 arguments were provided
  KOKKOS_INLINE_FUNCTION explicit ParArrayGeneric(
                                  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:123:35: note: candidate constructor template not viable: requires single argument 'state', but 3 arguments were provided
  KOKKOS_INLINE_FUNCTION explicit ParArrayGeneric(const State &state)
                                  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:64:3: note: candidate constructor not viable: requires 0 arguments, but 3 were provided
  ParArrayGeneric() = default;
```

I'm not sure where this error comes from nor why we didn't catch this in the existing tests. Using a `ParArary#D` seems like a usecase we should provide.

Any thoughts @lroberts36 

(Probably independently but related) our default access pattern to variables like
```
w(IPR, k, j, i + 1) ;
// with
// enum { IV1 = 1, IV2 = 2, IV3 = 3, IPR = 4 };
```
does not work any more resuling in the following error
```
FAILED: src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o 
/usr/bin/clang++ -DKOKKOS_DEPENDENCE -I/home/pgrete/src/athenapk/external/parthenon/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/src/generated -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src -I/home/pgrete/src/athenapk/external/Kokkos/core/src/../../tpls/desul/include -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/containers/src -I/home/pgrete/src/athenapk/external/Kokkos/containers/src -I/home/pgrete/src/athenapk/build-vscode/parthenon/Kokkos/algorithms/src -I/home/pgrete/src/athenapk/external/Kokkos/algorithms/src -fopenmp-simd -O3 -DNDEBUG -march=skylake-avx512 -mtune=skylake-avx512 -std=c++17 -MD -MT src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o -MF src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o.d -o src/CMakeFiles/athenaPK.dir/refinement/gradient.cpp.o -c /home/pgrete/src/athenapk/src/refinement/gradient.cpp
/home/pgrete/src/athenapk/src/refinement/gradient.cpp:36:43: error: no matching function for call to object of type 'const ParArrayND<double>' (aka 'const ParArrayGeneric<View<double ******, Kokkos::LayoutRight, Kokkos::HostSpace>, parthenon::empty_state_t>')
          Real eps = std::sqrt(SQR(0.5 * (w(IPR, k, j, i + 1) - w(IPR, k, j, i - 1))) +
                                          ^
/home/pgrete/src/athenapk/build-vscode/parthenon/src/generated/config.hpp:82:19: note: expanded from macro 'SQR'
#define SQR(x) ( (x) * (x) )
                  ^
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:175:37: note: candidate template ignored: requirement 'all_implement<integral ((unnamed enum at /home/pgrete/src/athenapk/src/refinement/../main.hpp:31:1), int, int, int), void>::value' was not satisfied [with Args = <(unnamed enum at /home/pgrete/src/athenapk/src/refinement/../main.hpp:31:1), int, int, int>]
  KOKKOS_FORCEINLINE_FUNCTION auto &operator()(Args... args) const {
```

I'm currently wondering if we should update AthenaPK or update Parthenon (whereas the latter would imply a certain style in downstream codes). Any thoughts anyone?

Ping @jdolence @lroberts36 @Yurlungur @forrestglines

**Comment by Yurlungur** [comment]
These both sound like bugs to me. I'm pretty sure both generic accessors and constructors should work with both `ParArrayND` and `ParArray#D`. @lroberts36 ?

**Comment by Yurlungur** [comment]
☝️ by which I mean bugs in `parthenon` obviously, not in `AthenaPK`.

**Comment by lroberts36** [comment]
Based on the error message it looks like `n_rho` and `n_pres` are `double`s. Is that actually the case? If so, the requirement that the constructor takes integral types could be relaxed in `parthenon`, although we would have to think about if this is a safe thing to do in general. @pgrete I can't find the `AthenaPK` code to look more carefully, is it available somewhere?

**Comment by Yurlungur** [comment]
I'm surprised that the `double`s weren't automatically downcast?

**Comment by lroberts36** [comment]
Didn't notice the second error. I think that one can also be fixed by removing the requirement that all values passed to the accessor are integral as well. I think passing an integral `enum` should be something that is supported.

**Comment by lroberts36** [comment]
It is a template based check for integral types and I don't know when that gets resolved during compilation relative to when the compiler would perform automatic down casting. It is easy to remove these requirements on the types, although I think it is a bit dangerous to have variadic templates that just accept anything.

**Comment by lroberts36** [comment]
Maybe we should just do `std::is_integral<T>::value | std::is_enum<T>::value`. I am not convinced that we should let people initialize array bounds with `double`s, etc.

**Comment by Yurlungur** [comment]
I think it's pretty safe to allow doubles. If you don't check for it, the compiler should downcast, since the template forwards it all to integer-based methods.

**Comment by lroberts36** [comment]
I think allowing `double`s can potentially result in code that can have subtle bugs due to rounding during the implicit downcast. IMO, it would be better if downstream users had to explicitly cast if they want this behavior. That being said, if this is done in many places and it is a lot of work to change, we could just allow floating point types as well. 

If we want to go down that path, it is probably just changing a couple of `std::is_integral<T>` to `std::is_convertible<T, std::size_t>::value`. I believe this should take care of the `enum` issues as well.

**Comment by pgrete** [comment]
Thanks for the quick replies!

This `double` was actually a bug on our part, doh...
https://gitlab.com/theias/hpc/jmstone/athena-parthenon/athenapk/-/blob/main/src/hydro/srcterms/tabular_cooling.cpp#L588
`const Real n_rho = pin->GetInteger("cooling", "test_n_rho");`
I only read the Get**Integer** part and assumed the front would be `auto`.
So don't mind that error.

As for the `enum`, the quick fix (and what I originally implemented) was using `constexpr int` instead. However, there were issues with Cuda <11.2, see https://gitlab.com/theias/hpc/jmstone/athena-parthenon/athenapk/-/blob/main/src/main.hpp#L12
Now with more recent Cuda versions out I'm inclined to just switch on our end.
Nevertheless, I think that we should allow `enum`s to be used for indices.

**Comment by lroberts36** [comment]
> This `double` was actually a bug on our part, doh...
> https://gitlab.com/theias/hpc/jmstone/athena-parthenon/athenapk/-/blob/main/src/hydro/srcterms/tabular_cooling.cpp#L588
> `const Real n_rho = pin->GetInteger("cooling", "test_n_rho");`
> I only read the Get**Integer** part and assumed the front would be `auto`.
> So don't mind that error.

I think I am pretty happy with the behavior that we got here. The initial error message from the compiler was pretty informative (at least for a template related error message) 
```
...
/home/pgrete/src/athenapk/external/parthenon/src/parthenon_array_generic.hpp:130:3: note: candidate template ignored: requirement 'all_implement<integral (double, double), void>::value' was not satisfied [with Args = <double, double>, $1 = 0, $2 = 0]
  ParArrayGeneric(const std::string &label, Args... args)
 ...
```
and this pointed to a potential future bug in the downstream code (since just casting from `int` to `double` to `int` is I think guaranteed to give back the original value since the mantissa of a `double` is larger than the size of an `integer`, but if `Real` is set to `float` then this set of operations is not guaranteed to give back the original value). I will put up a PR today that fixes the `enum` bug but I think I will leave out accepting `double`s.

**Comment by Yurlungur** [comment]
> I think I am pretty happy with the behavior that we got here. The initial error message that we got from the compiler was pretty informative (at least for a template related error message)

Fair enough. I defer to good code smells over free-wheeling flexibility. :P
